# THIS NEEDS TO BE UPDATED FOR ACCURATE STATS
MAX_WEEK = 6
START_WEEK = 1

WEEK = "WEEK"
POINTS_FOR = "PF"
POINTS_AGAINST = "PA"
MAX_POINTS_FOR = "MPF"
WINS = "WINS"
EXPECTED_WINS = "EXPECTED_WINS"
MATCHUP_ID = "matchup_id"
ROSTER_ID = "roster_id"
USER_ID = "user_id"
METADATA = "metadata"
TEAM_NAME = "team_name"
DISPLAY_NAME = "display_name"
MATCHUPS = "matchups"
POINTS = "points"
OWNER_ID = "owner_id"
ROSTER_REPEAT_PREFIX = "roster_"